services:
  dubarr:
    image: ghcr.io/neutrinus/dubarr:main
    container_name: dubarr
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./videos:/app/videos
      - ./output:/app/output
      - ./models:/app/models
      # Mount cache volume to /data/cache
      - dubarr_cache:/data/cache
    environment:
      - PUID=1000
      - PGID=1000
      - HF_TOKEN=${HF_TOKEN}
      - TARGET_LANGS=${TARGET_LANGS:-pl}
      - DEBUG=${DEBUG:-0}
      - VERBOSE=${VERBOSE:-0}
    restart: unless-stopped

volumes:
  dubarr_cache:
